import { createSlice } from "@reduxjs/toolkit";

// Initial state for the user slice
const initialState = {
  userInfo: null,
  isLoggedIn: false,
};

// Create a slice with reducers for updating state
const userSlice = createSlice({
  name: "user",
  initialState,
  reducers: {
    setUser: (state, action) => {
      state.userInfo = action.payload;
      state.isLoggedIn = true;
    },
    logout: (state) => {
      state.userInfo = null;
      state.isLoggedIn = false;
    },
  },
});

// Export the actions generated by createSlice
export const { setUser, logout } = userSlice.actions;

// Export the reducer to be added to the store
export default userSlice.reducer;
